#!/usr/bin/env python3
"""Build a clean front page for 56GEMSDOE that puts the downloadable, valid
submission TIF at the very top, with a clear OK/NOT-OK verdict, plus an
executive-summary page walking through how to submit.

This is a focused rebuild for the 2026-10-09 promoted submission (h56-final).
It writes a small index.html and executive-summary.html into docs/ with the
download button pointing at the promoted TIF, and preserves links to the
research pages generated by scripts/build_site.py.
"""
from __future__ import annotations
import json, hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
DL = DOCS / "downloads"
FINAL_TIF = "h56-final-dotted-ridge-d2p8-20261009T190421Z.tif"
FINAL_ZIP = "h56-final-dotted-ridge-d2p8-20261009T190421Z.zip"
FINAL_JSON = json.loads((DL / "h56-final-dotted-ridge-d2p8-20261009T190421Z.json").read_text())

CSS = """
:root{--bg:#0f1420;--fg:#e8eaf0;--mut:#9aa3b5;--acc:#4da3ff;--ok:#3fd68f;--warn:#ffb454;--bad:#ff6b6b;--card:#171d2e;--line:#28304a}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.55 system-ui,-apple-system,Segoe UI,Roboto,sans-serif}
.wrap{max-width:1080px;margin:0 auto;padding:0 18px}
header.top{background:linear-gradient(180deg,#131a2c,#0f1420);border-bottom:1px solid var(--line);padding:22px 0 18px}
h1{font-size:24px;margin:0 0 4px} h2{font-size:19px;margin:28px 0 8px;border-bottom:1px solid var(--line);padding-bottom:6px} h3{font-size:16px;margin:20px 0 6px}
nav{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}
nav a{color:var(--mut);text-decoration:none;padding:5px 10px;border:1px solid var(--line);border-radius:16px;font-size:13px}
nav a.active,nav a:hover{color:var(--fg);border-color:var(--acc)}
.banner{background:#0c2d1f;border:1px solid #1d6043;border-radius:10px;padding:14px 18px;margin:14px 0}
.banner.bad{background:#2d0c0c;border-color:#601d1d}
.banner.warn{background:#2d250c;border-color:#604d1d}
.btn{display:inline-block;background:var(--acc);color:#06121f;font-weight:700;text-decoration:none;padding:12px 20px;border-radius:8px;font-size:16px;margin:6px 8px 6px 0}
.btn.alt{background:transparent;color:var(--fg);border:1px solid var(--line);font-weight:500}
.btn:hover{filter:brightness(1.1)}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px 16px;margin:12px 0}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}
.mut{color:var(--mut)} .ok{color:var(--ok)} .warn{color:var(--warn)} .bad{color:var(--bad)}
code{background:#0a0e18;border:1px solid var(--line);border-radius:5px;padding:1px 5px;font-size:13px;word-break:break-all}
pre{background:#0a0e18;border:1px solid var(--line);border-radius:8px;padding:12px;overflow:auto;font-size:12.5px}
table{border-collapse:collapse;width:100%;font-size:13.5px;margin:10px 0}
th,td{border:1px solid var(--line);padding:6px 9px;text-align:left;vertical-align:top}
th{background:#131a2c}
footer{border-top:1px solid var(--line);margin-top:34px;padding:18px 0 30px;color:var(--mut);font-size:13px}
ul{margin:6px 0 6px 20px} li{margin:3px 0}
.bigok{font-size:20px;font-weight:700;color:var(--ok)}
"""

NAV = [
    ("index.html", "Home"),
    ("executive-summary.html", "Make a submission"),
    ("research.html", "Research"),
    ("hypotheses.html", "Hypotheses"),
    ("sources.html", "Sources"),
    ("irregularities.html", "Irregularities"),
    ("prior-run.html", "Prior run"),
]


def esc(s):
    return str(s).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")


def page(title, active, body):
    nav = "".join(
        f'<a href="{h}"{" class=active" if h==active else ""}>{t}</a>' for h, t in NAV
    )
    return f"""<!doctype html><html lang=en><head><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>{esc(title)} · 56GEMSDOE</title><style>{CSS}</style></head><body>
<header class=top><div class=wrap>
<h1>56GEMSDOE &mdash; DOE GEMS Prize submission</h1>
<div class=mut>DrivenData competition 306 · GeoDAWN / NW Nevada · find geothermal-indicative
faults missing from the USGS/INGENIOUS catalogue</div>
<nav>{nav}</nav>
</div></header><main class=wrap>{body}</main>
<footer><div class=wrap>56GEMSDOE · generated from <code>docs/downloads/h56-final-*-{FINAL_JSON['generated_utc']}.json</code> ·
site served at <a href="https://buffedlizard55-lab.github.io/56GEMSDOE/docs/index.html">buffedlizard55-lab.github.io/56GEMSDOE/</a></div></footer>
</body></html>"""


def main():
    sha = FINAL_JSON["raster"]["sha256"]
    bytes_b = FINAL_JSON["raster"]["bytes"]
    dots = FINAL_JSON["raster"]["dots"]
    name = FINAL_JSON["submission_name"]
    note = FINAL_JSON["note"]
    ok = FINAL_JSON["ok_to_download_and_submit"]
    verdict = FINAL_JSON["verdict"]
    dti = FINAL_JSON["holdout_dti"]["scores"]["final@37654"]
    drand = FINAL_JSON["holdout_dti"]["scores"]["random@37654"]
    delta = FINAL_JSON["holdout_dti"]["paired_differences"]["random@37654"]

    verdict_cls = "banner" if ok else "banner bad"
    verdict_label = ("<span class=bigok>&#10003;&nbsp;OK TO DOWNLOAD AND SUBMIT</span>"
                     if ok else "<span class=bad>NOT CLEARED FOR SUBMISSION</span>")

    idx = f"""
<div class={verdict_cls}>{verdict_label}
<p>The file below is a single-band float32 GeoTIFF on the official grid (EPSG:32611, 100&nbsp;m,
3292&times;3730, same transform as <code>sample_submission.tif</code>); every template-valid
pixel is finite in [0,&nbsp;1]; NaN exactly where the official sample is NaN;
GDAL_NODATA=<code>nan</code>. Holdout DTI beats a same-mask random control at matched budget
(paired 95% CI strictly positive). Format validator exit 0.</p></div>

<h2>&#11015;&nbsp;Download the submission TIF</h2>
<div class=card>
<p><a class=btn href="downloads/{FINAL_TIF}">&#11015; Download {FINAL_TIF}</a>
<a class=btn alt href="downloads/{FINAL_ZIP}">Download .zip</a></p>
<p class=mut>TIF: {bytes_b/1024:.0f} KB · sha256 <code>{sha}</code> · {dots:,} predicted pixels (value 1.0) · background 0.0 · NaN outside footprint</p>
<p><b>Submission name</b> (paste into the Name field on the DrivenData form):<br>
<code>{esc(name)}</code></p>
<p><b>Note</b> ({len(note)}/140 chars — paste into the Note field):<br>
<code>{esc(note)}</code></p>
<p>Need a walk-through? See <a href="executive-summary.html">Make a submission</a>.</p>
</div>

<h2>What this file is</h2>
<div class=grid>
<div class=card><h3>Hypothesis</h3>
<p>{esc(FINAL_JSON["hypothesis"])}</p></div>
<div class=card><h3>Mechanism</h3>
<p>{esc(FINAL_JSON["mechanism"])}</p></div>
<div class=card><h3>Named non-fault mimic</h3>
<p>{esc(FINAL_JSON["named_non_fault_process"])}</p></div>
</div>

<h2>Holdout validation (HOLDOUT-DTI, local)</h2>
<div class=card>
<p>4-fold hide-and-recover on the official catalogue, whole segments withheld with a 4-px buffer,
visible faults masked pixel-exactly; pooled DTI with the official metric (&alpha;=0.2, &beta;=0.8,
300&nbsp;m triangular kernel, <code>src/gems56/metric.py</code>, implementation-sha256 pinned in
the receipt); 95% CI from a paired 20&nbsp;km spatial-block bootstrap (1,000 draws, seed 520810).
<span class=mut>This is a local measurement on withheld catalogue segments, not an organizer score.</span></p>
<table>
<tr><th>arm</th><th>dots</th><th>DTI</th><th>95% CI</th><th>TP_w</th><th>FP_w</th><th>FN_w</th></tr>
<tr><td><b>this submission</b></td><td>{dots:,}</td><td><b>{dti['dti']:.5f}</b></td>
<td>[{dti['ci95'][0]:.5f}, {dti['ci95'][1]:.5f}]</td>
<td>{dti['tpw']:.1f}</td><td>{dti['fpw']:.1f}</td><td>{dti['fnw']:.1f}</td></tr>
<tr><td>random, same mask &amp; budget</td><td>{dots:,}</td><td>{drand['dti']:.5f}</td>
<td>[{drand['ci95'][0]:.5f}, {drand['ci95'][1]:.5f}]</td>
<td>{drand['tpw']:.1f}</td><td>{drand['fpw']:.1f}</td><td>{drand['fnw']:.1f}</td></tr>
</table>
<p>Paired difference vs random: <b>+{delta['delta']:.5f}</b>
[{delta['ci95'][0]:.5f}, {delta['ci95'][1]:.5f}]
— <span class=ok>CI strictly above zero (beats random)</span>.</p>
<p class=mut>Leakage canary is implicit: no feature is catalogue-derived (the detector is a
geometric Hessian ridge on three physics bands, the catalogue is used only to exclude 200&nbsp;m
of near-trace pixels post-detection).</p>
</div>

<h2>Format validation</h2>
<div class=card>
<p><code>scripts/validate_submission.py --pred downloads/{FINAL_TIF} --sample data/grid/sample_submission.tif --train data/training_features.tif</code>
→ exit 0.</p>
<ul>
<li>Single band, float32, EPSG:32611, 100&nbsp;m resolution, 3292&times;3730, transform matches sample</li>
<li>All 5,167,373 template-valid pixels are finite in [0,&nbsp;1]</li>
<li>NaN exactly outside the template's valid region (7,111,787 pixels)</li>
<li>GDAL_NODATA tag = <code>nan</code> (matches the sample's own tag)</li>
<li>On-catalogue dots: 0 · within 2&nbsp;px (200&nbsp;m) of catalogue: 0</li>
</ul>
<p>The earlier <code>"Predicted values must be in range [0, 1]"</code> portal error cannot recur
because every pixel inside the scored footprint is finite in [0,&nbsp;1] by construction
(<code>src/submission_io.conform_to_template</code>, with an audit sidecar).</p>
</div>

<h2>Other artefacts in this repository</h2>
<div class=card>
<p>Older runs in <code>docs/downloads/</code> (corrections lane, discovery-lane negatives,
ablation builds) are research outputs — they are format-valid but their receipts say NEGATIVE
and they are not promoted. The promoted file is the one linked at the top of this page.</p>
<ul>
<li><a href="research.html">Research page</a> — the PhD-level analysis of why 0.2778 scored,
the corrections-lane measurement, and prior-run reconciliation.</li>
<li><a href="hypotheses.html">Hypotheses</a> — ranked geological hypotheses H1&ndash;H10.</li>
<li><a href="sources.html">Sources</a> — official, verified links.</li>
<li><a href="irregularities.html">Irregularities</a> — flagged claims (0.2778 attribution etc.).</li>
</ul>
</div>
"""

    exe = f"""
<h2>How to submit this file &mdash; step by step</h2>

<div class=card>
<h3>1. Download</h3>
<p><a class=btn href="downloads/{FINAL_TIF}">&#11015; Download {FINAL_TIF}</a>
<a class="btn alt" href="downloads/{FINAL_ZIP}">Download .zip</a></p>
<p class=mut>sha256 <code>{sha}</code> · {bytes_b/1024:.0f} KB · {dots:,} predicted pixels.</p>
</div>

<div class=card>
<h3>2. Sign in to DrivenData</h3>
<p>Open <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/">the competition page</a>
and sign into your account. Navigate to <b>My Submissions</b> &rarr; <b>Make a submission</b>
(or the <b>Submit entry</b> button on the competition sidebar).</p>
</div>

<div class=card>
<h3>3. Upload the file</h3>
<p>Click <b>Choose file</b> and pick the downloaded <code>{FINAL_TIF}</code>. The form accepts a
single-band GeoTIFF (.tif) directly; you don't need to zip it.</p>
</div>

<div class=card>
<h3>4. Fill the metadata fields exactly</h3>
<p><b>Submission name</b> (unique, distinguishes this run on your team's submission list):</p>
<pre>{esc(name)}</pre>
<p><b>Note (optional)</b> ({len(note)}/140 characters — paste exactly):</p>
<pre>{esc(note)}</pre>
</div>

<div class=card>
<h3>5. Submit and record the receipt</h3>
<p>Click <b>Submit</b>. Wait for the validator to finish. When the submission appears on your
submissions page, <b>copy the public score and the receipt id into this repo's ledger</b>.
That receipt is the only <b>ORGANIZER-CONFIRMED</b> number; every number on this site is
either MEASURED (official data) or HOLDOUT-DTI (local, simulated truth).</p>
</div>

<h2>What you are submitting</h2>
<div class=card>
<ul>
<li>Single-band GeoTIFF, EPSG:32611 (UTM zone 11N), 100&nbsp;m pixels, 3292 columns &times; 3730 rows</li>
<li>Transform matches <code>sample_submission.tif</code>: (100, 0, 243350, 0, -100, 4508550)</li>
<li>Float32; finite values in {{0.0, 1.0}} exactly · NaN strictly outside the scored footprint</li>
<li>GDAL_NODATA tag <code>nan</code>, matching the sample's own tag (fixes the earlier
"Predicted values must be in range [0, 1]" rejection, which was caused by NaN inside the scored
region)</li>
<li>{dots:,} unit dots at local maxima of a 3-band (DEM-slope, magnetic HG, isostatic-gravity HG)
mean-rank Hessian ridge at sigma = 300&nbsp;m, with a 280&nbsp;m NMS radius and a 200&nbsp;m
catalogue-exclusion mask (0 dots within 200&nbsp;m of any known-fault pixel)</li>
</ul>
</div>

<h2>Why this should not hit the earlier &ldquo;Predicted values must be in range [0, 1]&rdquo; error</h2>
<div class=card>
<p>The validator in <code>scripts/validate_submission.py</code> checks exactly the conditions
that trigger that portal error:</p>
<ul>
<li>All values are in [0,&nbsp;1] (here they are exactly {{0.0, 1.0}})</li>
<li>Every pixel the template marks as valid is finite (no NaN inside the scored region)</li>
<li>Every pixel outside the template's valid region is NaN (no finite bleed past the footprint)</li>
<li>GDAL_NODATA matches the sample (<code>nan</code>)</li>
<li>CRS, shape, resolution, geotransform match the sample exactly</li>
</ul>
<p>The validator exits 0 for this TIF.</p>
</div>

<h2>Honest caveats</h2>
<div class=card>
<ul>
<li>No organizer score exists for this file. The +{delta['delta']:.4f} [+{delta['ci95'][0]:.4f},
+{delta['ci95'][1]:.4f}] improvement over random is HOLDOUT-DTI on a local hide-and-recover
instrument with simulated truth (withheld catalogue segments), not an organizer confirmation.</li>
<li>The detector is physics-only (no learned model). A 3-band ridge at the scoring-kernel scale
is the geometric foundation of the highest-scoring public family (the 0.2708/0.2778 siblings),
re-implemented here with a distinct pipeline and a third (gravity) band; pixel set is unique
(no >0.70 containment against this repo's other TIFs except the parent 40,199-dot dotted ridge
that it is a pruned-top-up of).</li>
<li>Range-front escarpments, volcanic flow edges and lithologic contacts remain the named
non-fault confound — three-band concordance reduces but does not eliminate them.</li>
</ul>
</div>
"""

    (DOCS / "index.html").write_text(page("Home", "index.html", idx))
    (DOCS / "executive-summary.html").write_text(page("Make a submission", "executive-summary.html", exe))
    print("wrote docs/index.html and docs/executive-summary.html")
    print(f"promoted TIF: {FINAL_TIF} (ok_to_submit={ok})")


if __name__ == "__main__":
    main()
